In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('outputforwebsite.data')

In [5]:
df.sample(20)

,Statename,FIPS,Date,Days_from_Ref,RelativeMobility,CumulativeMobility,Actual-Predict,FatalityRA,CumFatality_Stayput,SchoolOpenNow1%,SchoolOpenNow2%,MaskMandate25%,MaskMandate50%,Shutdown1week,Shutdown2week,Population
1125,Texas,48,2020-5-5,43,-32.333333,25.726667,Actual,25.000000,995.000000,NaN,NaN,NaN,NaN,NaN,NaN,28995881
4505,North Carolina,37,2020-8-15,137,NaN,NaN,Actual,30.000000,2343.000000,NaN,NaN,NaN,NaN,NaN,NaN,10488084
1432,Ohio,39,2020-5-14,35,-28.333333,23.456667,Actual,50.600000,1534.000000,NaN,NaN,NaN,NaN,NaN,NaN,11689100
3598,New Jersey,34,2020-7-19,108,-22.000000,58.593333,Actual,14.400000,15706.000000,NaN,NaN,NaN,NaN,NaN,NaN,8882190
4179,Alabama,1,2020-8-5,129,-10.666667,106.870000,Actual,21.600000,1695.000000,NaN,NaN,NaN,NaN,NaN,NaN,4903185
4418,Iowa,19,2020-8-12,130,NaN,NaN,Actual,7.800000,953.000000,NaN,NaN,NaN,NaN,NaN,NaN,3155070
5188,Pennsylvania,42,2020-9-5,151,NaN,NaN,Prediction,18.578687,7764.327027,7764.327027,7764.327027,7764.327027,7764.327027,7764.327027,7764.327027,12801989
2655,Indiana,18,2020-6-20,73,3.000000,58.170000,Actual,15.600000,2536.000000,NaN,NaN,NaN,NaN,NaN,NaN,6732219
5352,Illinois,17,2020-9-10,156,NaN,NaN,Prediction,17.900210,8380.390630,8380.390630,8380.390630,8380.390630,8380.390630,8380.390630,8380.390630,12671821
1390,Florida,12,2020-5-13,50,-38.333333,26.566667,Actual,39.200000,1827.000000,NaN,NaN,NaN,NaN,NaN,NaN,21477737
1857,Georgia,13,2020-5-27,70,-31.000000,43.676667,Actual,32.000000,1933.000000,NaN,NaN,NaN,NaN,NaN,NaN,10617423
5491,Ohio,39,2020-9-14,158,NaN,NaN,Prediction,38.767639,4752.939826,4752.939826,4752.939826,4752.939826,4752.939826,4752.939826,4752.939826,11689100
3067,Kentucky,21,2020-7-2,93,-8.666667,71.133333,Actual,5.000000,581.000000,NaN,NaN,NaN,NaN,NaN,NaN,4467673
4732,Ohio,39,2020-8-22,135,NaN,NaN,Prediction,26.348067,4000.255873,4000.255873,4000.255873,4000.255873,4000.255873,4000.255873,4000.255873,11689100
4345,Washington,53,2020-8-10,121,-29.666667,80.390000,Actual,10.400000,1697.000000,NaN,NaN,NaN,NaN,NaN,NaN,7614893
5885,Connecticut,9,2020-9-26,187,NaN,NaN,Prediction,13.184230,4672.297913,4730.876414,4820.843623,4565.743215,4562.223680,4618.156967,4612.768031,3565287
4136,Connecticut,9,2020-8-4,134,-32.333333,90.543333,Actual,1.000000,4437.000000,NaN,NaN,NaN,NaN,NaN,NaN,3565287
3615,South Carolina,45,2020-7-19,112,-6.333333,91.480000,Actual,30.200000,1155.000000,NaN,NaN,NaN,NaN,NaN,NaN,5148714
2254,Arizona,4,2020-6-8,74,-26.000000,48.526667,Actual,17.200000,1053.000000,NaN,NaN,NaN,NaN,NaN,NaN,7278717
94,Rhode Island,44,2020-4-3,-14,NaN,NaN,Actual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1059361

Index(['Statename', ' FIPS', ' Date', ' Days_from_Ref', ' RelativeMobility',
       ' CumulativeMobility', ' Actual-Predict', ' FatalityRA',
       ' CumFatality_Stayput', ' SchoolOpenNow1%', 'SchoolOpenNow2%',
       'MaskMandate25%', ' MaskMandate50%', ' Shutdown1week', ' Shutdown2week',
       ' Population'],
      dtype='object')

In [8]:
df.dropna(subset=[" Shutdown2week"])

,Statename,FIPS,Date,Days_from_Ref,RelativeMobility,CumulativeMobility,Actual-Predict,FatalityRA,CumFatality_Stayput,SchoolOpenNow1%,SchoolOpenNow2%,MaskMandate25%,MaskMandate50%,Shutdown1week,Shutdown2week,Population
4521,New York,36,2020-8-16,140,NaN,NaN,Prediction,8.056252,32841.056252,32841.056252,32841.056252,32841.056252,32841.056252,32841.056252,32841.056252,26161672
4522,New Jersey,34,2020-8-16,136,NaN,NaN,Prediction,6.275814,15916.275814,15916.275814,15916.275814,15916.275814,15916.275814,15916.275814,15916.275814,8882190
4523,California,6,2020-8-16,137,NaN,NaN,Prediction,145.576575,11363.576575,11363.576575,11363.576575,11363.576575,11363.576575,11363.576575,11363.576575,39512223
4524,Texas,48,2020-8-16,146,NaN,NaN,Prediction,218.265820,10486.265820,10486.265820,10486.265820,10486.265820,10486.265820,10486.265820,10486.265820,28995881
4525,Florida,12,2020-8-16,145,NaN,NaN,Prediction,181.727113,9526.727113,9526.727113,9526.727113,9526.727113,9526.727113,9526.727113,9526.727113,21477737
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6133,Rhode Island,44,2020-10-3,169,NaN,NaN,Prediction,0.030066,1029.016969,1029.712598,1030.771509,1034.602684,1065.081915,1029.506446,1029.873859,1059361
6134,Iowa,19,2020-10-3,182,NaN,NaN,Prediction,20.637418,1583.743724,1625.925857,1697.616983,1529.192529,1523.974806,1574.378844,1574.378844,3155070
6135,Oklahoma,40,2020-10-3,176,NaN,NaN,Prediction,16.219197,1192.280983,1363.159289,1631.685203,910.458238,885.837334,1048.905070,1000.217862,3956971
6136,Kentucky,21,2020-10-3,186,NaN,NaN,Prediction,6.410275,1065.067808,1127.226593,1226.292225,1004.359590,978.359181,1046.744983,1038.640704,4467673
6137,US,0,2020-10-3,186,NaN,NaN,Prediction,3996.952642,278071.565504,313403.541643,369516.205904,227740.413225,218955.864880,261105.708668,253622.261642,0